-- Journey timeline events. Built by database/projects/journey.py. Safe to re-run.
SET NAMES utf8mb4;
DELETE FROM journey WHERE title_en IN ('Launched "Apex Finance" Platform', 'Promoted to Senior Software Engineer', 'AWS Certified Solutions Architect', 'Machine Learning Specialization');
INSERT INTO journey (date_en, date_ar, title_en, title_ar, description_en, description_ar, tag_en, tag_ar, tag_type, side, image, created_at) SELECT 'During university', 'أثناء الدراسة', 'Started freelancing', 'بداية العمل الحر', 'Small web projects on Upwork and Fiverr, and for people in my network, while studying Computer Science.', 'مشاريع ويب صغيرة على Upwork وFiverr ولأشخاص من شبكة معارفي أثناء دراستي لعلوم الحاسب.', 'CAREER', 'مسيرة مهنية', 'career', 'left', '/assets/images/journey/01-egypt-1.webp', '2019-01-01 12:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM journey WHERE title_en = 'Started freelancing');
INSERT INTO journey (date_en, date_ar, title_en, title_ar, description_en, description_ar, tag_en, tag_ar, tag_type, side, image, created_at) SELECT '2022', '2022', 'Data Analysis Professional Nanodegree', 'نانو ديجري تحليل البيانات الاحترافي', 'Government-sponsored scholarship from MCIT and Udacity. Projects included bike-share and medical no-show analyses in Python.', 'منحة حكومية من وزارة الاتصالات وUdacity، شملت مشاريع لتحليل بيانات مشاركة الدراجات والتغيب عن المواعيد الطبية بـ Python.', 'CERTIFICATE', 'شهادة', 'cert', 'right', '', '2022-06-01 12:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM journey WHERE title_en = 'Data Analysis Professional Nanodegree');
INSERT INTO journey (date_en, date_ar, title_en, title_ar, description_en, description_ar, tag_en, tag_ar, tag_type, side, image, created_at) SELECT '2022', '2022', 'B.Sc. in Computer Science, MUST', 'بكالوريوس علوم الحاسب، جامعة مصر للعلوم والتكنولوجيا', 'Graduated in Information Technology with a Computer Science major. Overall grade Very Good; graduation project graded Excellent.', 'تخرجت في تكنولوجيا المعلومات تخصص علوم الحاسب بتقدير عام جيد جدًا ومشروع تخرج بتقدير امتياز.', 'EDUCATION', 'تعليم', 'learning', 'left', '', '2022-07-01 12:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM journey WHERE title_en = 'B.Sc. in Computer Science, MUST');
INSERT INTO journey (date_en, date_ar, title_en, title_ar, description_en, description_ar, tag_en, tag_ar, tag_type, side, image, created_at) SELECT 'Oct – Dec 2022', 'أكتوبر – ديسمبر 2022', 'ML research internship in India', 'تدريب بحثي في تعلم الآلة بالهند', 'Machine and deep learning research at Vellore Institute of Technology, comparing VGG16, VGG19, InceptionV3 and Xception on fruit-disease images.', 'بحث في تعلم الآلة والتعلم العميق بمعهد فيلور للتكنولوجيا، لمقارنة نماذج VGG16 وVGG19 وInceptionV3 وXception على صور أمراض الفاكهة.', 'CAREER', 'مسيرة مهنية', 'career', 'right', '/assets/images/journey/02-india-1.webp', '2022-10-01 12:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM journey WHERE title_en = 'ML research internship in India');
INSERT INTO journey (date_en, date_ar, title_en, title_ar, description_en, description_ar, tag_en, tag_ar, tag_type, side, image, created_at) SELECT 'Jan 2024', 'يناير 2024', 'Moved to Dubai: first engineer at ALL-INKL''s Gulf branch', 'الانتقال إلى دبي: أول مهندس في فرع ALL-INKL بالخليج', 'Joined ALL-INKL.COM as the first software engineer at their first GCC branch, on Palm Jumeirah, working with teams in Dubai and Germany.', 'انضممت إلى ALL-INKL.COM كأول مهندس برمجيات في أول فرع لها في الخليج، في نخلة جميرا، بالعمل مع فرق في دبي وألمانيا.', 'CAREER', 'مسيرة مهنية', 'career', 'left', '/assets/images/journey/04-dubai-1.webp', '2024-01-01 12:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM journey WHERE title_en = 'Moved to Dubai: first engineer at ALL-INKL''s Gulf branch');
INSERT INTO journey (date_en, date_ar, title_en, title_ar, description_en, description_ar, tag_en, tag_ar, tag_type, side, image, created_at) SELECT 'Jan 2026', 'يناير 2026', 'Two years at ALL-INKL', 'عامان في ALL-INKL', 'Wrapped up two years building the KAS control panel and internal tools, and moved on to client work and my own products.', 'أنهيت عامين من تطوير لوحة تحكم KAS والأدوات الداخلية، وانتقلت إلى العمل مع العملاء ومنتجاتي الخاصة.', 'CAREER', 'مسيرة مهنية', 'career', 'right', '', '2026-01-15 12:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM journey WHERE title_en = 'Two years at ALL-INKL');
INSERT INTO journey (date_en, date_ar, title_en, title_ar, description_en, description_ar, tag_en, tag_ar, tag_type, side, image, created_at) SELECT '2026', '2026', 'Tech Lead at SeroEvents UAE', 'قائد تقني في SeroEvents الإمارات', 'Leading engineering: code review and releases, infrastructure and email, procurement, SEO and analytics, and the rebuild of the event platform.', 'أقود الجانب الهندسي: مراجعة الكود والإصدارات، والبنية التحتية والبريد، والمشتريات، وSEO والتحليلات، وإعادة بناء منصة الفعاليات.', 'CAREER', 'مسيرة مهنية', 'career', 'left', '/assets/images/journey/05-now-2.webp', '2026-09-20 12:00:00' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM journey WHERE title_en = 'Tech Lead at SeroEvents UAE');
