-- Redesign copy (Sept 2026). Safe to re-run.
-- Live server: mysql --default-character-set=utf8mb4 -u<user> -p <db> < database/updates/2026-09-27-redesign.sql
SET NAMES utf8mb4;
INSERT INTO translations (msgid, en, ar) VALUES
('hero_title', 'Software Engineer · AI Systems & Automation', 'مهندس برمجيات · أنظمة الذكاء الاصطناعي والأتمتة'),
('hero_headline', 'I build intelligent software.', 'أبني برمجيات ذكية.'),
('hero_desc', 'Production web systems end to end, and AI engineered to be trusted. Tech Lead at Sero Events UAE, building in English and Arabic.', 'أنظمة ويب متكاملة جاهزة للإنتاج، وذكاء اصطناعي مصمم ليكون موثوقًا. قائد تقني في Sero Events الإمارات، وأبني بالعربية والإنجليزية.'),
('btn_hire', 'Let''s talk', 'تواصل معي'),
('btn_projects', 'View my work', 'شاهد أعمالي'),
('home_explore', 'Explore', 'استكشف'),
('home_cta', 'Have a system to build or automate?', 'لديك نظام تريد بناءه أو أتمتته؟'),
('contact_heading', 'Let''s talk.', 'لنتحدث.'),
('contact_subtitle', 'Tell me about your project, your idea or the role you''re hiring for.', 'أخبرني عن مشروعك أو فكرتك أو الوظيفة التي توظّف لها.'),
('form_name_placeholder', 'Your name', 'اسمك'),
('form_email_placeholder', 'you@example.com', 'you@example.com'),
('form_message_placeholder', 'What are you building?', 'ما الذي تعمل على بنائه؟'),
('form_submit', 'Send message', 'أرسل الرسالة'),
('nav_blog', 'Journey', 'رحلتي'),
('journey_heading', 'My Journey', 'رحلتي'),
('footer_tagline', 'Software engineer building production web systems and AI you can trust. Based in Dubai.', 'مهندس برمجيات يبني أنظمة ويب جاهزة للإنتاج وذكاءً اصطناعيًا يمكن الوثوق به. مقيم في دبي.'),
('footer_pages', 'Pages', 'الصفحات'),
('footer_services', 'Services', 'الخدمات'),
('footer_contact', 'Contact', 'التواصل'),
('footer_location', 'Dubai, UAE', 'دبي، الإمارات'),
('footer_rights', 'All rights reserved.', 'جميع الحقوق محفوظة.'),
('footer_back_top', 'Back to top', 'العودة للأعلى'),
('about_heading', 'Engineer first. AI by design.', 'مهندس أولًا، والذكاء الاصطناعي بالتصميم.'),
('about_subtitle', 'I''m Omar, a software engineer from Egypt, based in Dubai. I build web systems end to end, from the database to the server they run on, and I bring AI into them with guardrails so people can actually trust the output.', 'أنا عمر، مهندس برمجيات من مصر مقيم في دبي. أبني أنظمة الويب من البداية للنهاية، من قاعدة البيانات حتى الخادم الذي تعمل عليه، وأدمج فيها الذكاء الاصطناعي بضوابط تجعل نتائجه جديرة بالثقة.'),
('about_pro_story_title', 'My story', 'قصتي'),
('about_pro_story', 'I started freelancing while studying Computer Science at MUST in Egypt: small projects on Upwork and Fiverr, and for people in my network. That taught me early what shipping for a real client means.\nAfter graduating I went to India for a machine learning research internship at VIT, comparing deep-learning models for detecting fruit disease. It was my first serious work with AI, and the reason I still care about how models behave in the real world.\nIn 2024 I moved to Dubai as the first software engineer at ALL-INKL.COM''s first branch in the Gulf, on Palm Jumeirah. For two years I built features for a hosting control panel used by thousands of customers, alongside engineers in Dubai and Germany.\nToday I''m Tech Lead at SeroEvents UAE, rebuilding their event platform, and I keep building AI tools on the side, like PitchProof, where the model can only cite claims a human has approved.', 'بدأت العمل الحر أثناء دراستي لعلوم الحاسب في جامعة مصر للعلوم والتكنولوجيا: مشاريع صغيرة على Upwork وFiverr ولأشخاص من شبكة معارفي. تعلمت مبكرًا ما يعنيه التسليم لعميل حقيقي.\nبعد التخرج سافرت إلى الهند لتدريب بحثي في تعلم الآلة بمعهد فيلور، قارنت فيه نماذج التعلم العميق لاكتشاف أمراض الفاكهة. كانت أول تجربة جادة لي مع الذكاء الاصطناعي، وهي سبب اهتمامي حتى اليوم بسلوك النماذج في العالم الحقيقي.\nفي 2024 انتقلت إلى دبي كأول مهندس برمجيات في أول فرع لـ ALL-INKL.COM في الخليج، في نخلة جميرا. لمدة عامين طورت خصائص للوحة تحكم استضافة يستخدمها آلاف العملاء، مع مهندسين في دبي وألمانيا.\nاليوم أعمل قائدًا تقنيًا في SeroEvents الإمارات لإعادة بناء منصة الفعاليات، وأواصل بناء أدوات ذكاء اصطناعي مثل PitchProof، حيث لا يستشهد النموذج إلا بادعاءات وافق عليها إنسان.'),
('about_skills_title', 'Skills & tools', 'المهارات والأدوات'),
('skill_ai', 'AI & Automation', 'الذكاء الاصطناعي والأتمتة'),
('journey_subtitle', 'From Egypt to India to Dubai: how I got here.', 'من مصر إلى الهند إلى دبي: كيف وصلت إلى هنا.')
ON DUPLICATE KEY UPDATE en = VALUES(en), ar = VALUES(ar);

-- AI & Automation skills (only what projects back up). Skipped if already present.
INSERT INTO skills (category, name_en, name_ar, sort_order)
SELECT * FROM (SELECT 'ai' c, 'LLM integration (Gemini)' e, 'دمج النماذج اللغوية (Gemini)' a, 1 o UNION ALL
               SELECT 'ai', 'Output validation (Zod)', 'التحقق من المخرجات (Zod)', 2 UNION ALL
               SELECT 'ai', 'Grounded generation', 'توليد مقيد بالمصادر', 3 UNION ALL
               SELECT 'ai', 'n8n automation', 'أتمتة n8n', 4 UNION ALL
               SELECT 'ai', 'TensorFlow / transfer learning', 'TensorFlow والتعلم بالنقل', 5) n
WHERE NOT EXISTS (SELECT 1 FROM skills s WHERE s.category = n.c AND s.name_en = n.e);

-- Visual Editor keys (INSERT IGNORE: re-running keeps edits made in the Visual Editor)
INSERT IGNORE INTO translations (msgid, en, ar) VALUES
('filter_all', 'All', 'الكل'),
('svc_heading', 'Services', 'الخدمات'),
('svc_subtitle', 'I design, build and run web systems and AI features for businesses, in English and Arabic. You work with one engineer who owns it end to end.', 'أصمم وأبني وأشغّل أنظمة ويب وخصائص ذكاء اصطناعي للشركات، بالعربية والإنجليزية. تتعامل مع مهندس واحد مسؤول عنها من البداية للنهاية.'),
('svc_ai_title', 'AI & Automation', 'الذكاء الاصطناعي والأتمتة'),
('svc_ai_text', 'AI features built with guardrails, and n8n workflows that take repetitive work off your team.', 'خصائص ذكاء اصطناعي مبنية بضوابط واضحة، ومسارات n8n تُخفف العمل المتكرر عن فريقك.'),
('svc_web_title', 'Web Development', 'تطوير الويب'),
('svc_web_text', 'Web applications and websites, from database to interface, in Laravel, PHP, JavaScript and React.', 'تطبيقات ومواقع ويب من قاعدة البيانات حتى الواجهة، باستخدام Laravel وPHP وJavaScript وReact.'),
('svc_bilingual_title', 'Bilingual Sites & CMS', 'مواقع ثنائية اللغة ونظام إدارة محتوى'),
('svc_bilingual_text', 'English and Arabic with proper right-to-left layout, and a CMS so you can edit content yourself.', 'عربي وإنجليزي مع اتجاه صحيح من اليمين لليسار، ونظام إدارة محتوى لتعدّل المحتوى بنفسك.'),
('svc_data_title', 'Database & Integrations', 'قواعد البيانات والتكاملات'),
('svc_data_text', 'Schema design, migrations, and connecting your system to payment, booking and other APIs.', 'تصميم قواعد البيانات والترحيل، وربط نظامك بخدمات الدفع والحجز وغيرها من الواجهات البرمجية.'),
('svc_maintenance_title', 'Maintenance & Fixes', 'الصيانة والإصلاحات'),
('svc_maintenance_text', 'Finding and fixing the bugs nobody can reproduce, updates, and keeping existing sites healthy.', 'اكتشاف وإصلاح الأخطاء التي يصعب تكرارها، والتحديثات، والحفاظ على كفاءة المواقع الحالية.'),
('svc_hosting_title', 'Deployment & Hosting', 'النشر والاستضافة'),
('svc_hosting_text', 'Linux servers, Docker, domains, DNS, SSL and email set up so your site runs reliably.', 'إعداد خوادم Linux وDocker والنطاقات وDNS وSSL والبريد ليعمل موقعك باستقرار.'),
('svc_cta', 'Have a project in mind?', 'لديك مشروع في ذهنك؟'),
('story_1_place', 'Egypt', 'مصر'),
('story_1_when', 'Until 2022', 'حتى 2022'),
('story_1_title', 'Where it started', 'البداية'),
('story_1_text', 'Studying Information Technology and Computer Science at MUST, and freelancing on the side: small projects on Upwork and Fiverr, and for people in my network. That is where I learned to ship for real clients.', 'درست تكنولوجيا المعلومات وعلوم الحاسب في جامعة مصر للعلوم والتكنولوجيا، وبدأت العمل الحر بجانب الدراسة: مشاريع صغيرة على Upwork وFiverr ولأشخاص من شبكة معارفي. هناك تعلمت التسليم لعملاء حقيقيين.'),
('story_2_place', 'India', 'الهند'),
('story_2_when', 'Oct – Dec 2022', 'أكتوبر – ديسمبر 2022'),
('story_2_title', 'Into AI research', 'إلى أبحاث الذكاء الاصطناعي'),
('story_2_text', 'After graduating, I travelled to Vellore Institute of Technology for a machine learning and deep learning research internship, comparing VGG16, VGG19, InceptionV3 and Xception on crop-disease datasets.', 'بعد التخرج سافرت إلى معهد فيلور للتكنولوجيا في تدريب بحثي في تعلم الآلة والتعلم العميق، قارنت فيه نماذج VGG16 وVGG19 وInceptionV3 وXception على بيانات أمراض المحاصيل.'),
('story_3_place', 'Egypt', 'مصر'),
('story_3_when', '2023', '2023'),
('story_3_title', 'Getting ready', 'الاستعداد'),
('story_3_text', 'Back home to sharpen my skills and prepare for the next big move.', 'عدت إلى الوطن لأطور مهاراتي وأستعد للخطوة الكبيرة التالية.'),
('story_4_place', 'Dubai', 'دبي'),
('story_4_when', '2024 – 2026', '2024 – 2026'),
('story_4_title', 'First engineer in the Gulf', 'أول مهندس في الخليج'),
('story_4_text', 'I moved to Dubai to join ALL-INKL.COM as the first software engineer at their first GCC branch, on Palm Jumeirah, building features for their hosting control panel, an in-app translation system and internal tools.', 'انتقلت إلى دبي لأنضم إلى ALL-INKL.COM كأول مهندس برمجيات في أول فرع لها في الخليج، في نخلة جميرا، وطورت خصائص للوحة تحكم الاستضافة ونظام ترجمة داخل التطبيق وأدوات داخلية.'),
('story_5_place', 'UAE', 'الإمارات'),
('story_5_when', 'Now', 'الآن'),
('story_5_title', 'Tech Lead, SeroEvents', 'قائد تقني في SeroEvents'),
('story_5_text', 'Today I lead technology at SeroEvents UAE, and keep building AI-powered tools on the side.', 'اليوم أقود الجانب التقني في SeroEvents الإمارات، وأواصل بناء أدوات مدعومة بالذكاء الاصطناعي.'),
('proj_count_label', 'projects', 'مشروعًا'),
('proj_search_ph', 'Search by name or tech...', 'ابحث بالاسم أو التقنية...'),
('proj_empty', 'No projects match your search.', 'لا توجد مشاريع مطابقة.'),
('card_cta', 'View case study', 'دراسة الحالة'),
('card_progress', 'Progress', 'نسبة الإنجاز'),
('card_live', 'Live site', 'الموقع المباشر'),
('about_chip', 'About me', 'نبذة عني'),
('about_fact_role', 'Tech Lead, SeroEvents', 'قائد تقني، SeroEvents'),
('about_fact_langs', 'Arabic · English', 'العربية · الإنجليزية'),
('about_badge_ai', 'AI systems', 'أنظمة ذكاء اصطناعي'),
('about_badge_stack', 'Full-stack & infra', 'تطوير متكامل وبنية تحتية'),
('about_stat_1', 'Shipping in production since', 'أعمل في بيئات إنتاج منذ'),
('about_stat_2', 'Projects built and shipped', 'مشروعًا منجزًا'),
('about_stat_3', 'Bilingual EN/AR products', 'منتجات ثنائية اللغة'),
('about_stat_4', 'Countries lived and worked in', 'دول عشت وعملت فيها'),
('about_story_link', 'Walk through my journey', 'تابع رحلتي'),
('about_how_title', 'How I work', 'طريقتي في العمل'),
('about_p1_title', 'Own it end to end', 'المسؤولية الكاملة'),
('about_p1_text', 'Schema, backend, frontend, and the Linux, Docker, DNS and SSL it runs on. I ship the whole thing, not a slice of it.', 'قاعدة البيانات والخادم والواجهة، وبيئة Linux وDocker وDNS وSSL التي تعمل عليها. أسلّم النظام كاملًا لا جزءًا منه.'),
('about_p2_title', 'Make AI trustworthy', 'ذكاء اصطناعي موثوق'),
('about_p2_text', 'Model output is untrusted input. I validate it, ground it in approved facts, and make the boundary visible to users.', 'مخرجات النموذج مدخلات غير موثوقة. أتحقق منها وأربطها بحقائق معتمدة وأجعل حدودها واضحة للمستخدم.'),
('about_p3_title', 'Build for change', 'البناء من أجل التغيير'),
('about_p3_text', 'Interfaces around vendors, append-only history instead of overwritten status, and decisions written down as ADRs.', 'واجهات حول المزودين، وسجل تاريخي بدل الحالات المتغيرة، وقرارات موثقة كسجلات معمارية.'),
('about_p4_title', 'Speak both languages', 'أتحدث اللغتين'),
('about_p4_text', 'Arabic and English with real right-to-left layout, across four products. Not a translation layer added at the end.', 'العربية والإنجليزية مع اتجاه صحيح من اليمين لليسار في أربعة منتجات، وليست ترجمة تُضاف في النهاية.'),
('about_exp_title', 'Experience & education', 'الخبرة والتعليم'),
('about_exp1_org', 'SeroEvents UAE', 'SeroEvents الإمارات'),
('about_exp1_role', 'Tech Lead', 'قائد تقني'),
('about_exp1_when', 'Now', 'الآن'),
('about_exp1_where', 'Dubai', 'دبي'),
('about_exp1_points', 'Lead the rebuild of the company website into a bilingual event platform for healthcare and scientific conferences (Next.js, TypeScript, PostgreSQL with Prisma).\nOwn the Git workflow: review, approve and merge every pull request, and keep the main branch ready to release.\nOwn infrastructure and releases: servers, environments and production deployments.\nRun company email: mailboxes, email domains and DNS, and the platform''s transactional email through Microsoft Graph.\nHandle IT procurement and vendor management: software licenses, servers, domains and hosting, and the integration between these services.\nResponsible for technical SEO, web analytics and event tracking, and performance monitoring: collecting the data, analysing it and acting on it.', 'أقود إعادة بناء موقع الشركة ليصبح منصة فعاليات ثنائية اللغة للمؤتمرات الطبية والعلمية (Next.js وTypeScript وPostgreSQL مع Prisma).\nأتولى إدارة سير العمل على Git: مراجعة كل طلبات الدمج (Pull Requests) واعتمادها ودمجها، والحفاظ على الفرع الرئيسي جاهزًا للإطلاق.\nأتولى البنية التحتية والإصدارات: الخوادم والبيئات والنشر على بيئة الإنتاج.\nأدير البريد الإلكتروني للشركة: صناديق البريد ونطاقات البريد وإعدادات DNS، والرسائل التلقائية للمنصة عبر Microsoft Graph.\nأتولى المشتريات التقنية وإدارة الموردين: تراخيص البرمجيات والخوادم والنطاقات والاستضافة، والربط بين هذه الخدمات.\nمسؤول عن تحسين محركات البحث التقني (SEO)، وتحليلات الويب وتتبع الأحداث، ومراقبة الأداء: جمع البيانات وتحليلها والعمل بناءً عليها.'),
('about_exp2_org', 'ALL-INKL.COM', 'ALL-INKL.COM'),
('about_exp2_role', 'Web Development Specialist', 'أخصائي تطوير ويب'),
('about_exp2_when', '2024 – 2026', '2024 – 2026'),
('about_exp2_where', 'Palm Jumeirah, Dubai', 'نخلة جميرا، دبي'),
('about_exp2_points', 'First software engineer at the company''s first branch in the Gulf, working with teams in Dubai and Germany.\nBuilt search, sorting and pagination once and reused it across the KAS hosting control panel.\nDesigned an in-app translation system with inline editing, msgid storage and per-string states.\nDiagnosed a bug nobody could reproduce by adding browser and device data to bug reports.', 'أول مهندس برمجيات في أول فرع للشركة في الخليج، بالعمل مع فرق في دبي وألمانيا.\nبنيت البحث والترتيب والترقيم مرة واحدة واستخدمتها عبر لوحة تحكم KAS بالكامل.\nصممت نظام ترجمة داخل التطبيق بتحرير مباشر وتخزين بالمعرفات وحالات لكل نص.\nشخّصت خطأً لم يستطع أحد تكراره بإضافة بيانات المتصفح والجهاز إلى البلاغات.'),
('about_exp3_org', 'Freelance & client work', 'العمل الحر والعملاء'),
('about_exp3_role', 'Sole developer', 'مطور منفرد'),
('about_exp3_when', 'Ongoing', 'مستمر'),
('about_exp3_where', 'Remote', 'عن بُعد'),
('about_exp3_points', 'Super Speed: bilingual corporate site with a right-click inline CMS, in native PHP.\nYaxiGo: rail booking platform with replaceable train and payment providers.\nFlow Egypt: bilingual real-estate site, from design to deployment.', 'Super Speed: موقع شركة ثنائي اللغة مع نظام إدارة محتوى بالنقر الأيمن بلغة PHP.\nYaxiGo: منصة حجز قطارات بمزودي قطارات ودفع قابلين للاستبدال.\nFlow Egypt: موقع عقارات ثنائي اللغة من التصميم حتى النشر.'),
('about_exp4_org', 'Vellore Institute of Technology', 'معهد فيلور للتكنولوجيا'),
('about_exp4_role', 'ML & Deep Learning Research Intern', 'متدرب بحثي في تعلم الآلة'),
('about_exp4_when', 'Oct – Dec 2022', 'أكتوبر – ديسمبر 2022'),
('about_exp4_where', 'India', 'الهند'),
('about_exp4_points', 'Compared VGG16, VGG19, InceptionV3 and Xception on Indian fruit-disease datasets using transfer learning.', 'قارنت نماذج VGG16 وVGG19 وInceptionV3 وXception على بيانات أمراض الفاكهة باستخدام التعلم بالنقل.'),
('about_exp5_org', 'MUST', 'جامعة مصر للعلوم والتكنولوجيا'),
('about_exp5_role', 'B.Sc. Information Technology, Computer Science', 'بكالوريوس تكنولوجيا المعلومات، علوم الحاسب'),
('about_exp5_when', '2022', '2022'),
('about_exp5_where', 'Egypt', 'مصر'),
('about_exp5_points', 'Graduated with Very Good; graduation project graded Excellent. Freelancing on Upwork and Fiverr alongside.\nData Analysis Professional Nanodegree, MCIT & Udacity scholarship (2022).', 'تخرجت بتقدير جيد جدًا ومشروع تخرج بتقدير امتياز، مع العمل الحر على Upwork وFiverr.\nنانو ديجري تحليل البيانات، منحة وزارة الاتصالات وUdacity (2022).'),
('about_lang_title', 'Languages', 'اللغات'),
('about_lang1_name', 'Arabic', 'العربية'),
('about_lang1_level', 'Native', 'اللغة الأم'),
('about_lang2_name', 'English', 'الإنجليزية'),
('about_lang2_level', 'Fluent', 'بطلاقة'),
('about_lang3_name', 'German', 'الألمانية'),
('about_lang3_level', 'Beginner', 'مبتدئ'),
('about_cta_title', 'Want to build something together?', 'هل تريد أن نبني شيئًا معًا؟'),
('about_cta_text', 'Tell me about the system you have in mind.', 'أخبرني عن النظام الذي تفكر فيه.'),
('svc_hero_title', 'Software that works, from idea to production.', 'برمجيات تعمل، من الفكرة حتى التشغيل.'),
('svc_start', 'Start a project', 'ابدأ مشروعًا'),
('svc_what_title', 'What I can do for you', 'ما يمكنني تقديمه لك'),
('svc_included', 'What''s included', 'ما الذي يشمله'),
('svc_ai_includes', 'AI features with validated, grounded output\nn8n workflows that connect your tools\nStructured extraction from text and documents', 'خصائص ذكاء اصطناعي بمخرجات متحقق منها ومقيدة بالمصادر\nمسارات n8n تربط أدواتك ببعضها\nاستخراج منظم للبيانات من النصوص والمستندات'),
('svc_web_includes', 'Custom web applications and dashboards\nAdmin panels and content management\nREST APIs and third-party integrations', 'تطبيقات ويب ولوحات تحكم مخصصة\nلوحات إدارة ونظام إدارة محتوى\nواجهات REST وتكاملات مع خدمات خارجية'),
('svc_bilingual_includes', 'Arabic and English with proper right-to-left layout\nInline or dashboard CMS your team can use\nTranslation workflow that needs no deploy', 'العربية والإنجليزية مع اتجاه صحيح من اليمين لليسار\nنظام إدارة محتوى مباشر أو عبر لوحة تحكم لفريقك\nسير عمل للترجمة دون الحاجة إلى نشر جديد'),
('svc_data_includes', 'Schema design and safe migrations\nPayment, booking and email integrations\nAudit logs and reporting', 'تصميم قواعد البيانات وترحيل آمن\nتكامل مع الدفع والحجز والبريد\nسجلات تدقيق وتقارير'),
('svc_maintenance_includes', 'Investigating and fixing hard-to-reproduce bugs\nUpdates and security hardening\nPerformance improvements', 'تتبع وإصلاح الأخطاء صعبة التكرار\nالتحديثات وتعزيز الأمان\nتحسين الأداء'),
('svc_hosting_includes', 'VPS, Docker and CyberPanel setup\nDomains, DNS, SSL and business email\nDeployments, backups and monitoring', 'إعداد الخوادم وDocker وCyberPanel\nالنطاقات وDNS وSSL وبريد الأعمال\nالنشر والنسخ الاحتياطي والمراقبة'),
('svc_process_title', 'How we''ll work together', 'كيف سنعمل معًا'),
('svc_step1_title', 'Discover', 'الاستكشاف'),
('svc_step1_text', 'We talk through the problem, your users and what success looks like.', 'نناقش المشكلة ومستخدميك وما يعنيه النجاح بالنسبة لك.'),
('svc_step2_title', 'Plan', 'التخطيط'),
('svc_step2_text', 'A clear scope, the architecture and a timeline you can hold me to.', 'نطاق واضح ومعمارية وجدول زمني يمكنك محاسبتي عليه.'),
('svc_step3_title', 'Build', 'البناء'),
('svc_step3_text', 'Working software early and often, so you see progress every week.', 'برمجيات تعمل مبكرًا وباستمرار، لترى التقدم كل أسبوع.'),
('svc_step4_title', 'Launch', 'الإطلاق'),
('svc_step4_text', 'Deployment, domains, SSL and email, set up and tested in production.', 'النشر والنطاقات وSSL والبريد، مُعدة ومختبرة في بيئة الإنتاج.'),
('svc_step5_title', 'Support', 'الدعم'),
('svc_step5_text', 'Fixes, updates and improvements after launch, plus a CMS so you''re not stuck waiting on me.', 'إصلاحات وتحديثات وتحسينات بعد الإطلاق، مع نظام إدارة محتوى حتى لا تنتظرني في كل تعديل.'),
('svc_why_title', 'Why work with me', 'لماذا تعمل معي'),
('svc_why1_title', 'One engineer, backed by AI agents', 'مهندس واحد، تدعمه وكلاء ذكاء اصطناعي'),
('svc_why1_text', 'You talk to the person who writes the code, sets up the server and fixes the bug, so nothing gets lost in hand-offs. Behind me is a set of AI agents and automations set up for each project, which speed up the work and review, test and check every change before it ships.', 'تتحدث مع الشخص الذي يكتب الكود ويجهز الخادم ويصلح الخطأ، فلا يضيع شيء بين الأطراف. ويدعمني فريق من وكلاء الذكاء الاصطناعي والأتمتة مُعدّ خصيصًا لكل مشروع، يسرّع العمل ويراجع كل تعديل ويختبره ويتحقق منه قبل إطلاقه.'),
('svc_why2_title', 'RTL and LTR, done right', 'من اليمين لليسار ومن اليسار لليمين، بإتقان'),
('svc_why2_text', 'I''ve shipped four products that work in both directions: Arabic right-to-left and English left-to-right, with mirrored layouts, typography tuned for each script, and language switching that keeps users where they were. It''s part of the design from day one, not patched on later.', 'أطلقت أربعة منتجات تعمل في الاتجاهين: العربية من اليمين لليسار والإنجليزية من اليسار لليمين، مع تخطيطات معكوسة وخطوط مضبوطة لكل لغة، وتبديل للغة يُبقي المستخدم في مكانه. هذا جزء من التصميم منذ اليوم الأول، وليس إضافة لاحقة.'),
('svc_why3_title', 'Built to be handed over', 'مصمم ليُسلَّم'),
('svc_why3_text', 'Documentation, deployment notes and a CMS your team can use, so the project doesn''t depend on me.', 'توثيق وملاحظات للنشر ونظام إدارة محتوى يستخدمه فريقك، حتى لا يعتمد المشروع عليّ.'),
('svc_faq_title', 'Common questions', 'أسئلة شائعة'),
('svc_faq1_q', 'Do you work remotely?', 'هل تعمل عن بُعد؟'),
('svc_faq1_a', 'Yes. I''m based in Dubai and work with clients remotely, in any time zone.', 'نعم. أقيم في دبي وأعمل مع العملاء عن بُعد في أي منطقة زمنية.'),
('svc_faq2_q', 'Can you work on my existing website?', 'هل يمكنك العمل على موقعي الحالي؟'),
('svc_faq2_a', 'Yes. I can fix bugs, add features, improve performance or move it to a new server without starting over.', 'نعم. يمكنني إصلاح الأخطاء وإضافة خصائص وتحسين الأداء أو نقله لخادم جديد دون البدء من الصفر.'),
('svc_faq3_q', 'Do you handle hosting, domains and email?', 'هل تتولى الاستضافة والنطاقات والبريد؟'),
('svc_faq3_a', 'Yes. I can set up the server, domain, SSL and business email, and keep deployments and backups running.', 'نعم. أجهز الخادم والنطاق وSSL وبريد الأعمال، وأتابع النشر والنسخ الاحتياطي.'),
('svc_faq4_q', 'What do you need from me to start?', 'ماذا تحتاج مني للبدء؟'),
('svc_faq4_a', 'A short description of what you want to build and who it''s for. We''ll shape the rest together in the first call.', 'وصف مختصر لما تريد بناءه ولمن. وسنكمل الباقي معًا في أول مكالمة.'),
('contact_chip', 'Contact', 'تواصل'),
('contact_status', 'Open to freelance projects and collaborations', 'متاح للمشاريع الحرة والتعاون'),
('contact_or', 'Reach me directly', 'تواصل معي مباشرة'),
('contact_copy', 'Copy email', 'نسخ البريد'),
('contact_copied', 'Copied', 'تم النسخ'),
('contact_reply', 'Usually replies within a day', 'عادةً أرد خلال يوم'),
('contact_form_title', 'Send me a message', 'أرسل لي رسالة'),
('contact_error', 'Something went wrong. Check your email address, or email me directly.', 'حدث خطأ. تأكد من بريدك الإلكتروني أو راسلني مباشرة.'),
('contact_topic_label', 'What''s it about?', 'عن ماذا تريد التحدث؟'),
('contact_topic_1', 'AI & automation', 'الذكاء الاصطناعي والأتمتة'),
('contact_topic_2', 'Web app', 'تطبيق ويب'),
('contact_topic_3', 'Fix or improve a site', 'إصلاح أو تطوير موقع'),
('contact_topic_4', 'Hosting & email', 'الاستضافة والبريد'),
('contact_topic_5', 'Something else', 'شيء آخر'),
('journey_timeline_title', 'Milestones', 'محطات بارزة'),
('journey_timeline_sub', 'The jobs, projects and studies along the way, newest first.', 'الوظائف والمشاريع والدراسة على طول الطريق، من الأحدث إلى الأقدم.'),
('journey_filter_career', 'Career', 'المسيرة المهنية'),
('journey_filter_project', 'Projects', 'المشاريع'),
('journey_filter_learning', 'Education', 'التعليم');
